### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by m-p-3** [codebox/star-charts#2]
Hi, I'm not very knowledgeable about Python and I wanted to use this utility to generate a chart and after some testing, I figured I needed to use Python 2.7, and trying to using Python 3.6 wouldn't generate the chart correctly.

Would it be possible to add a mention about some prerequisite in the readme to save some time for other newcomers like me? Thanks for your work on this!

**Comment by codebox** [comment]
Good idea, thanks - I have added a note at the bottom of the project page
